apiVersion: langchain/v1
kind: AgentExecutor
description: >
  A simple chat agent
service_name: ChatBot
version: 0.1
input_type: BaseInput
spec:
  llm:
    provider: openai
    model: gpt-4o-mini
    temperature: 0.7
  tools: []
  agent_type: openai-functions
  system_prompt: >
    You are a helpful assistant. Work with the user to assist them in whatever they need.
  tasks:
    - name: action_task
      task_no: 1
      description: Chat with user
      instructions: >
        Work with the user to assist them in whatever they need.
