apiVersion: langchain/v1
kind: ChatAgent
description: >
  A weather chat agent
service_name: WeatherBot
version: 0.1
input_type: BaseMultiModalInput
spec:
  llm:
    provider: openai
    model: gpt-4o
    temperature: 0.7
  tools:
    - WeatherPlugin
  agent_type: openai-functions
  system_prompt: >
    You are a helpful assistant.
