apiVersion: langchain/v1
kind: AgentExecutor
description: >
  A number adder
service_name: AdderAgent
version: 0.1
input_type: NumbersInput
output_type: AddOutput
spec:
  llm:
    provider: openai
    model: gpt-4o-mini
    temperature: 0.7
  tools: []
  agent_type: openai-functions
  system_prompt: >
    You are a helpful assistant. Add the following two numbers together: {{number_1}} {{number_2}}
  tasks:
    - name: action_task
      task_no: 1
      description: Add two number
      instructions: >
        Add the following two numbers together
        {{number_1}} {{number_2}}
