name: Build and Push ao

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-and-push-ao.yml
      - ao.Dockerfile
      - 'shared/ska_utils/**'
      - 'src/orchestrators/assistant-orchestrator/orchestrator/**'
      - '!**.md'
  pull_request:
    # All PRs, including stacked PRs

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./src/orchestrators/assistant-orchestrator/orchestrator
        run: make sync
      - name: Run lint
        working-directory: ./src/orchestrators/assistant-orchestrator/orchestrator
        run: make lint

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./src/orchestrators/assistant-orchestrator/orchestrator
        run: make sync
      - name: Run tests with coverage
        working-directory: ./src/orchestrators/assistant-orchestrator/orchestrator
        run: make coverage

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: tests
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./src/orchestrators/assistant-orchestrator/orchestrator
        run: make sync
      - name: bump version with hatch
        id: bump_version
        working-directory: ./src/orchestrators/assistant-orchestrator/orchestrator
        run: |
          git pull
          git checkout ${{ github.ref_name }}
          uv run hatch version dev
          git config --global user.name "Teal Agents Bot"
          git config --global user.email " "
          git commit -am "bump dev version [skip ci]"
          git push --set-upstream origin ${{ github.ref_name }}
      - name: Extract version with hatch
        id: extract_version
        working-directory: ./src/orchestrators/assistant-orchestrator/orchestrator
        run: |
          VERSION=$( uv run hatch version )
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/teal-agents/ao:${{ steps.extract_version.outputs.VERSION }} -f ao.Dockerfile .
          docker tag ghcr.io/teal-agents/ao:${{ steps.extract_version.outputs.VERSION }} ghcr.io/teal-agents/ao:latest
      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: |
          docker push ghcr.io/teal-agents/ao:${{ steps.extract_version.outputs.VERSION }}
          docker push ghcr.io/teal-agents/ao:latest
